# Change these first
owner: SENOA-N # Your GitHub organization or username, where this repository lives
repo: mtn.webex # The name of this repository
user-agent: SENOA-N
sites:
  - name: Webex

assignees: # Users to assign downtime issues (optional)
  - SENOA-N
status-website: # Status website (optional)
  # cname: upptime.js.org # Custom domain CNAME
  baseUrl: /mtn.webex # where "repo" is your repository name
  name: MTN Webex Status# Status website title
