# Change these first
owner: SENOA-N # Your GitHub organization or username, where this repository lives
repo: mtn.webex # The name of this repository
user-agent: SENOA-N
sites:
  - name: Webex
    url: https://google.com

assignees: # Users to assign downtime issues (optional)
  - SENOA-N
status-website: # Status website (optional)
  # cname: upptime.js.org # Custom domain CNAME
  baseUrl: /mtn.webex # where "repo" is your repository name
  name: MTN Webex Status # Status website title
  themeUrl: assets/light.css
  logoUrl: assets/MTN-Light.png
status-website:
  introTitle: "**MTN Webex Status** Look at MTN Webex uptime and incident report"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages.
  favicon: assets/MTN-Light.png
