# Change these first
owner: SENOA-N # Your GitHub organization or username, where this repository lives
repo: mtn.webex # The name of this repository
user-agent: SENOA-N
sites:
  - name: Webex
    url: https://status.webex.com/status.json
    # check: "{'status':{'indicator':'red'}}"
assignees: # Users to assign downtime issues (optional)
  - SENOA-N

status-website: # Status website (optional)
  # cname: upptime.js.org # Custom domain CNAME
  baseUrl: /mtn.webex # where "repo" is your repository name
  name: MTN Webex Status # Status website title
  themeUrl: https://senoa-n.github.io/mtn.webex/light.css
  theme: light
  logoUrl: https://senoa-n.github.io/mtn.webex/MTN-Light.png # https://github.com/SENOA-N/mtn.webex/assets/MTN-Light.svg
  introTitle: "**MTN Webex Status** Live incident and status updates"
  introMessage: "This portal gives live updates of MTN Webex services and is currently in the **test phase**. **Ignore all status and incident updates on this page.**"
  favicon: https://senoa-n.github.io/mtn.webex/MTN-Light.png
  faviconSvg: https://senoa-n.github.io/mtn.webex/MTN-Light.svg

